import { Navbar } from '@/components/Navbar'
import { TaskProvider } from '../context/TasksContext'
import { Inter } from 'next/font/google'
import { Toaster } from './Toaster'
import './globals.css'


import { Layout } from '../components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <TaskProvider>
          <Navbar />
          <Layout>
            {children}
          </Layout>


          <Toaster />
        </TaskProvider>

      </body>
    </html>
  )
}
